name: Base Pipeline
run-name: ${{ github.actor }} is active here
on:
  push:
    branches:
      - main

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - run: echo "generating in ${{ runner.os }}"
      - run: echo "runnig by ${{ github.actor }}"
      
      - name: Install SSHPass
        run: sudo apt install sshpass
      
      - name: Hello
        run: echo hello world
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build